"""
Filename: drone_rotor.py

Summary:
    Rotor models to reflect physically feasible outputs generated by rotors. May include rotor uncertainties, signal noise and delays due to air dynamics. 
    Control input may require aggressive motor force, however, the rotor may not acheive the same.

Author: Yiming Zhang
Date: 2024-09-22
"""

import numpy as np
import drone_parameters as params
from dataclasses import dataclass
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

import drone_propeller

class Rotor:
    def __init__(self, propeller: drone_propeller.Propeller) -> None:
        pass

    def inject_uncertainties(self):
        pass

    def make_delay(self):
        pass

    def make_noise(self):
        pass
