# training process related parameters
learning_rate_phi: 0.0005
learning_rate_h: 0.0005
frequency_h: 4
fine_tune_epoch_h: 300
num_epochs: 200
alpha: 0.1    # weight of cross entropy loss
warmup_epoch: 5  # number of warmup steps before introducing the cross entropy loss
gamma: 10.0    # normalization of a
spectral_norm: 2.0    # normalization
is_dynamic_environment: True    # flag to adapt to environment with matrix a, False equivalent to a = ones(size)


# configuration used in the NF paper
# learning_rate_phi: 0.0005
# learning_rate_h: 0.001
# frequency_h: 2
# fine_tune_epoch_h: 200000 # never triggered
# num_epochs: 1000  # the paper actually choose the best model at 200 epochs
# alpha: 0.1    # weight of cross entropy loss
# warmup_epoch: 1  # number of warmup steps before introducing the cross entropy loss
# gamma: 10.0    # normalization of a
# spectral_norm: 2.0    # normalization
# is_dynamic_environment: True    # flag to adapt to environment with matrix a, False equivalent to a = ones(size)
